### ISSUE TITLE
Link to actual code is broken

### ISSUE THREAD

**Issue by oliver-batchelor** [lingjie0206/lingjie0206.github.io#2]
It links to here - but the link to the actual zip file is broken:

https://i.cs.hku.hk/~nlchen/curvefusion/

**Comment by lingjie0206** [comment]
It seems the system was crashed. You can also find a copy here: https://drive.google.com/file/d/1MD9Y1vYLurEPhXCnn3OkUMUEOBf8cyJJ/view?usp=sharing
